#!/bin/sh

# check if there are changes in packages
# Packages require a build before commit to ensure that types are up to date
if git diff --cached --name-only | grep -q "^packages"; then
  echo "Building packages ..."
  pnpm run build:packages
  pnpm run build:client
  pnpm run build:game-server
else
  echo "No changes detected in packages"
fi

# game-server require a test before push to ensure that tests are passing
pnpm run game-server test