import { IPlayer } from 'interfaces/core/IPlayer';

export const you: IPlayer = {
  seat: 6,
  name: 'me',
  stack: 1000,
  bet: 0,
  hole: ['AS', 'AD'],
  hand: 'THREE OF A KIND',
  status: 'action',
  isYou: true,
};
export const otherUsers: IPlayer[] = [
  {
    seat: 2,
    name: 'player2',
    stack: 1000,
    bet: 0,
    hole: ['Blue_Back', 'Blue_Back'],
    hand: null,
    status: 'playing',
    isYou: false,
  },
  {
    seat: 3,
    name: 'player3',
    stack: 1000,
    bet: 0,
    hole: ['Blue_Back', 'Blue_Back'],
    hand: null,
    status: 'AWAY',
    isYou: false,
  },
  {
    seat: 4,
    name: 'player4',
    stack: 1000,
    bet: 0,
    hole: ['Blue_Back', 'Blue_Back'],
    hand: null,
    status: 'WAITING',
    isYou: false,
  },
  {
    seat: 7,
    name: 'player5',
    stack: 1000,
    bet: 0,
    hole: ['Blue_Back', 'Blue_Back'],
    hand: null,
    status: 'playing',
    isYou: false,
  },
  {
    seat: 8,
    name: 'player6',
    stack: 1000,
    bet: 0,
    hole: ['Blue_Back', 'Blue_Back'],
    hand: null,
    status: 'playing',
    isYou: false,
  },
  {
    seat: 9,
    name: 'player7',
    stack: 1000,
    bet: 0,
    hole: ['Blue_Back', 'Blue_Back'],
    hand: null,
    status: 'playing',
    isYou: false,
  },
  {
    seat: 10,
    name: 'player8',
    stack: 1000,
    bet: 0,
    hole: ['Blue_Back', 'Blue_Back'],
    hand: null,
    status: 'playing',
    isYou: false,
  },
];
